sudo: false

language: node_js

node_js:
  - 0.12
  - 3
  - 4
  - 5

script:
  - npm run depcheck
  - npm run depcheck-json
  - npm run lint
  - npm run test-coverage
  - cat ./coverage/coverage.json | ./node_modules/codecov.io/bin/codecov.io.js

before_deploy:
  - ./node_modules/.bin/patch-version
  - gem install mime-types -v 2.6.2

deploy:
  - provider: npm
    skip_cleanup: true
    email: "lijunle@gmail.com"
    api_key:
      secure: "dEwnWZyvE95Amn3Ivcftk9wlDnRrNS2roVXREamsEJI3Rdilim7iHsINeVW/hZIv6VGepETKdSZ+nbyY/Du4rFkMyimHFBM9KkHgw46J7cf3juwZChzna/qOY+DniwGgikFscL+XAuKNx6Rv8xX4dD28TNoYzL00AtDhHJKla3E="
    on:
      tags: true
      node: 5
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: Uiilnj7sn8+KEgCMOByMdvCVARfAhvZGUvVrP1oijJBzrMr/YV5lPjH2Hph5IaJuvKKKagXXxqmcspkeiT/kaQA9TVg7VYh+B9DqhKiDxAkBYwMLgiPmnqDTh5ZGNOnnltVxhBI/qRDXpTj1i92VvloVlCcKQ3/M5mqlJi0j+8w=
    on:
      tags: true
      node: 5
