environment:
  matrix:
  - nodejs_version: 0.12
  - nodejs_version: 4
  - nodejs_version: 6
  - nodejs_version: 7

install:
  - ps: Install-Product node $env:nodejs_version
  - npm -g install npm@3 && set PATH=%APPDATA%\npm;%PATH%
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run depcheck
  - npm run depcheck-json
  - npm run lint
  - npm test

build: off
